# Generated by Django 2.0.3 on 2018-03-22 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrycode', models.CharField(help_text='Enter Country Code. e.g. USA - ISO alpha-3', max_length=3, verbose_name='ISO alpha-3')),
                ('iso2', models.CharField(default='', max_length=2, verbose_name='ISO alpha-2')),
                ('countryprefix', models.IntegerField(help_text='Enter Country Prefix. e.g. 1', verbose_name='Prefix')),
                ('countryname', models.CharField(help_text='Enter Country Name. e.g. United States', max_length=240, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'dialcode_country',
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('prefix', models.IntegerField(help_text='enter prefix', primary_key=True, serialize=False)),
                ('destination', models.CharField(help_text='enter destination', max_length=180)),
                ('carrier_name', models.CharField(help_text='enter carrier name', max_length=180)),
                ('prefix_type', models.IntegerField(choices=[(0, 'Landline'), (1, 'Mobile'), (2, 'NGN (Non Geographic Numbers)')], default=1, help_text='select prefix type', verbose_name='prefix type')),
                ('country_id', models.ForeignKey(blank=True, db_column='country_id', help_text='select country', null=True, on_delete=django.db.models.deletion.CASCADE, to='country_dialcode.Country', verbose_name='country code')),
            ],
            options={
                'verbose_name': 'prefix',
                'verbose_name_plural': 'prefixes',
                'db_table': 'dialcode_prefix',
                'ordering': ['prefix'],
            },
        ),
    ]
